### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [MJeekhof/gather#5]
(Meets Expectations) Overall, nice work.

Remember to make more and smaller commits, with messages that summarize the changes that were made. Look at some popular JavaScript open source projects' commits for some examples. Also, remember to use es6 features like object shorthand whenever possible.

Otherwise, your code is clean and easy to follow, nice work!

**Comment by MJeekhof** [comment]
Thanks for your review and comment. I'll keep them in mind!
